// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNuh2dmPfJciX82IJKF-2ZP-aRUW6VjU',
    appId: '1:563769826998:web:c23586df0ad244376f9017',
    messagingSenderId: '563769826998',
    projectId: 'authtutorial-5d420',
    authDomain: 'authtutorial-5d420.firebaseapp.com',
    storageBucket: 'authtutorial-5d420.appspot.com',
    measurementId: 'G-WWZQ00X089',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AwE0hR24Ngw1K5PqXX9PyFSnt53hbIs',
    appId: '1:563769826998:android:65ad61f08b2087126f9017',
    messagingSenderId: '563769826998',
    projectId: 'authtutorial-5d420',
    storageBucket: 'authtutorial-5d420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoh9J1O82-Hykxn_stqjh_JN6utr_sTQY',
    appId: '1:563769826998:ios:27b272380deae7eb6f9017',
    messagingSenderId: '563769826998',
    projectId: 'authtutorial-5d420',
    storageBucket: 'authtutorial-5d420.appspot.com',
    iosBundleId: 'com.example.loginScreenAgain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoh9J1O82-Hykxn_stqjh_JN6utr_sTQY',
    appId: '1:563769826998:ios:94474e85ceb2000a6f9017',
    messagingSenderId: '563769826998',
    projectId: 'authtutorial-5d420',
    storageBucket: 'authtutorial-5d420.appspot.com',
    iosBundleId: 'com.example.loginScreenAgain.RunnerTests',
  );
}
